[package]
name = "cuckatoo-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Core Cuckatoo algorithms and data types"
license.workspace = true
repository.workspace = true

[dependencies]

[dev-dependencies]
