[package]
name = "cuckatoo-miner"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "CLI runner for Cuckatoo mining"
license.workspace = true
repository.workspace = true

[dependencies]
cuckatoo-core = { path = "../cuckatoo-core" }
